### ISSUE TITLE
Please explain in the About

### ISSUE THREAD

**Issue by pcav** [fiftysevendegreesofrad/sdna_qgis_plugin#2]
what is sDNA, so the casual user can quickly understand what is the use of the plugin.

**Comment by fiftysevendegreesofrad** [comment]
Hi, both of these fixed, for the purpose of QGIS repo inclusion should I re upload the plugin to plugins.qgis.org?

**Comment by fiftysevendegreesofrad** [comment]
Or wait to hear back about any other issues?

**Comment by pcav** [comment]
It's up to you. As soon as the issue is fixed, I can publish it.

**Comment by fiftysevendegreesofrad** [comment]
Ok, done.  Wasn't sure how to change the uploaded version so I deleted and uploaded again.  Thank you.
