### ISSUE TITLE
Requires sDNA version 3 error

### ISSUE THREAD

**Issue by ziziqt** [fiftysevendegreesofrad/sdna_qgis_plugin#3]
I am running QGIS 4e1cf3c installed via osgeo4win 64bit.

Upon installation of the plugin it requires sDNA version 3, but on the sDNA download link there is no version 3 see this link http://www.cf.ac.uk/sdna/wp-content/downloads/?C=M;O=D

![image](https://cloud.githubusercontent.com/assets/16465366/12215306/1571567a-b6bf-11e5-82b5-2d32c23dac86.png)

**Comment by fiftysevendegreesofrad** [comment]
Hi, sorry about this - sDNA v3 will be out in beta within the next month.  The QGIS plugin approval process was quicker than I thought so currently we have the plugin but not yet the thing it connects to!

**Comment by anitagraser** [comment]
Downloads are here now http://www.cf.ac.uk/sdna/wp-content/downloads/experimental/

**Comment by fiftysevendegreesofrad** [comment]
As Anita says, downloads are at the above link.  When the software moves out of beta they will be moved to the parent folder.
