### ISSUE TITLE
sdnaintegral.py is not run correctly

### ISSUE THREAD

**Issue by anitagraser** [fiftysevendegreesofrad/sdna_qgis_plugin#4]
Just installed sDNA_setup_win_v3_1_alpha0.msi in the default location C:\Program Files (x86)\sDNA. Everything appears fine in the toolbox but running the Integral Analysis tool results in the following error (problem with space in path?):

![screenshot 2016-03-14 20 49 59](https://cloud.githubusercontent.com/assets/590385/13757769/61048c84-ea26-11e5-8360-bfc960f0dc71.png)

**Comment by fiftysevendegreesofrad** [comment]
Thank you for this report.  Please try again with the latest version of sDNA 3.2.alpha2
http://www.cf.ac.uk/sdna/wp-content/downloads/experimental/

**Comment by anitagraser** [comment]
Thank you, now it's running.
