### ISSUE TITLE
“System.AccessViolationException” occurred when I start the sDNA License manager

### ISSUE THREAD

**Issue by wangyoucao577** [fiftysevendegreesofrad/sdna_qgis_plugin#5]
I want to use the sDNA. So that I installed the sDNA_setup_win_v2.3.msi on my OS. But when I open the sDNA License manager to try to register this software, this exception occurred. I captured a screenshot as the following:

![1](https://cloud.githubusercontent.com/assets/1905370/16074151/be48d164-331b-11e6-8002-f0e142e0c350.png)

I also tried to run as administrator and run this program in compatibility mode for "windows XP/Vista", but it's always occurred.

My running environment: 
Win7 x64 on Vmware11, 4GB memory
ArcGIS 10.2
Python 2.7.11

**Comment by fiftysevendegreesofrad** [comment]
Hi
I have recently fixed some bugs of this nature.
Please can you try again with the latest version 3.4 beta 4.  From the downloads page it's in the experimental folder.
http://www.cf.ac.uk/sdna/wp-content/downloads/experimental/

**Comment by fiftysevendegreesofrad** [comment]
I just spotted you're on VMware - sorry this is not supported or tested - but still try the latest beta as it may fix the issue.

**Comment by wangyoucao577** [comment]
@fiftysevendegreesofrad  I have tried the latest version 3.4 beta 4, and it works. Thank you very much! 
By the way,it's ok within my VMware, and I think it's the same in vmware or real machine, isn't it?

**Comment by fiftysevendegreesofrad** [comment]
In theory yes.  And theory and practice are the same, in theory.  Thank you for reporting back, glad it worked.
