### ISSUE TITLE
Runtime error with large network system in ArcGIS

### ISSUE THREAD

**Issue by kimonkrenz** [fiftysevendegreesofrad/sdna_qgis_plugin#7]
While trying to run an integral analysis on a large system of 1,2million segments in ArcGIS, the tool produces consistently the same windows runtime error message. Trials with smaller systems work fine.

### Windows Error Message:
"Microsoft Visual C++ Runtime Library
Runtime Error!

Program: C:\Python27\ArcGIS10.2\python.exe

abnormal program termination"

### Integral Analysis Message Log:
"Executing: sDNAIntegral GE_Model_sDNAPrepare C:\Users\Documents\ArcGIS\Default.gdb\Model_sDNAPrepare_sDNAInt2 true false false false # # EUCLIDEAN 500 false false EUCLIDEAN Link # # # # # # # #
Start Time: Thu Mar 23 17:02:13 2017
Running script sDNAIntegral...
Running external command: "C:\Python27\ArcGIS10.2\python.exe" "C:\Program Files (x86)\sDNA\bin\\sdnaintegral.py" --im "net=C:/Users/Documents/ArcGIS/Default.gdb/Model_sDNAPrepare" --om "net=C
:/Users/Documents/ArcGIS/Default.gdb/Model_sDNAPrepare_sDNAInt2" "start_gs=;end_gs=;metric=EUCLIDEAN;custommetric=;disable=;intermediates=;oneway=;;origweight=;destweight=;weight_type=Link;ra
dii=500;radmetric=EUCLIDEAN;;nojunctions;nohull"

Using XYTolerance of input feature class: 0.001000
Using ZTolerance of input feature class: 0.001000
sDNA sdnaintegral config: start_gs=;end_gs=;metric=EUCLIDEAN;custommetric=;disable=;intermediates=;oneway=;;origweight=;destweight=;weight_type=Link;radii=500;radmetric=EUCLIDEAN;;nojunctions;nohull;a
rcxytol=0.001000;arcztol=0.001000;
Loading DLL C:\Program Files (x86)\sDNA\\sdna_vs2008.dll
  Using default of euclidean link centres for euclidean analysis
  Using xytolerance=0.001, ztolerance=0.001
Input has 1200000 rows
Creating geometry output C:/Users/Documents/ArcGIS/Default.gdb/Model_sDNAPrepare_sDNAInt2
Creating feature class Model_sDNAPrepare_sDNAInt2 in C:/Users/Documents/ArcGIS/Default.gdb
Output z-values: ENABLED
Reading features from C:/Users/Documents/ArcGIS/Default.gdb/Model_sDNAPrepare
Reading features from C:/Users/Documents/ArcGIS/Default.gdb/Model_sDNAPrepare
sDNA processing
  sDNA is running in 32-bit mode
  Building network and checking for tolerance errors...
  Running sDNA Integral calculation...
External command completed
Process did not complete successfully
Completed script sDNAIntegral...
Failed to execute (sDNAIntegral).
Failed at Thu Mar 23 18:01:29 2017 (Elapsed Time: 50 minutes 17 seconds)"

### System setup:
MacBook Pro 
Processor: 2,5 GHz Intel Core i5
Memory: 8 GB 1600 MHz DDR3
Graphic: Intel HD Graphics 4000 1536 MB
### On Parallels 10.1.1:
Windows 7 Professional on Parallels
Processor: 2,5 GHz Intel Core i5
Memory: 4 GB

### ArcGIS 
Version: 10.2.2 for Desktop (ArcMap 10.2.2.3552)
License: Advanced

<img width="183" alt="screen shot 2017-03-23 at 18 02 36" src="https://cloud.githubusercontent.com/assets/3910804/24264908/b4849bb6-0ff9-11e7-8440-17e3ca5773f5.png">

**Comment by fiftysevendegreesofrad** [comment]
Thank you for the comprehensive report.  My first suspicion is you have run out of memory but sDNA failed to spot this.

Is your copy of Windows 64-bit? If so please try installing Arcgis 64 bit background processing and running the same analysis in 64 bit mode. 

If this is not easy then you could test the theory by running the same thing you already did but logging memory usage as you go, in Task Manager if you're there to keep an eye on it, or another utility if not.

(Unfortunately in 3.4.5 there is a different bug in writing output from large networks in 64 bit processing. I have a fix for that ready here, so if *that* one affects you I'll push out a new release).
