### ISSUE TITLE
Windows Installation Error

### ISSUE THREAD

**Issue by ztratner** [fiftysevendegreesofrad/sdna_qgis_plugin#8]
sDNA installer crashes before doing anything. Here is the readout from the crash. Attempting to install on Windows 7.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	msiexec.exe
  Application Version:	5.0.7601.17514
  Application Timestamp:	4ce79d93
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.18409
  Fault Module Timestamp:	5315a05a
  Exception Code:	c06d007e
  Exception Offset:	000000000000940d
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	ddfe
  Additional Information 2:	ddfed6a41b2b48a14594f2f7a2614f69
  Additional Information 3:	06df
  Additional Information 4:	06dfa11467e4e84b51c266019da3cbdd

**Comment by fiftysevendegreesofrad** [comment]
Sorry, not sure what happened here. Closing old issues as we now have a working install on widows 10/11.
